Simple Linear Regression

There are five basic steps when you’re implementing linear regression:

* Import the packages and classes you need.
* Provide data to work with and eventually do appropriate transformations.
* Create a regression model and fit it with existing data.
* Check the results of model fitting to know whether the model is satisfactory.
* Apply the model for predictions.




In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')

In [13]:
x=np.array([10,20,30,40,50,60]).reshape((-1,1))
y=np.array([11,22,33,44,55,66])
print(x)
print(y)



[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
[11 22 33 44 55 66]


In [14]:
from sklearn import linear_model
reg=LinearRegression()
reg.fit(x,y)


LinearRegression()

In [16]:
r_sqrt=reg.score(x,y)
print('coefficient of determination: ',r_sqrt)
slope= reg.coef_
print('slope is: ', slope)
intercept= reg.intercept_
print('intercept: ', intercept)

coefficient of determination:  1.0
slope is:  [1.1]
intercept:  -1.4210854715202004e-14


In [19]:
y_pred=reg.predict(x)
y_pred

array([11., 22., 33., 44., 55., 66.])